### ISSUE TITLE
Problem installing: tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by holdenlee** [slinderman/pypolyagamma#25]
When I do `pip install pypolyagamma` I get the following error: 
```
    Complete output from command python setup.py egg_info:
    Downloading GSL...
    Extracting to deps/gsl
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-stJiJZ/pypolyagamma/setup.py", line 69, in <module>
        with tarfile.open(gsltarpath, 'r') as tar:
      File "/usr/lib/python2.7/tarfile.py", line 1680, in open
        raise ReadError("file could not be opened successfully")
    tarfile.ReadError: file could not be opened successfully
```

**Comment by slinderman** [comment]
I just updated `pypolyagamma` on PyPi.  It should now have the correct download link for GSL.  Can you please try running `pip install --upgrade --no-cache-dir pypolyagamma` now? This should download the latest version and try to install.

Note: I'm having trouble getting this to work on Python 3.7 due to a change in cython, but it should work on Python 3.6.  I need to distribute different .cpp files for Python 3.7, but I haven't figured out how to do so yet.

**Comment by slinderman** [comment]
Great, glad to hear it!
