### ISSUE TITLE
PyPolyaGamma instance is not pickle-able

### ISSUE THREAD

**Issue by gwgundersen** [slinderman/pypolyagamma#41]
**EDIT:** Sorry, I just saw https://github.com/slinderman/pypolyagamma/issues/33. My solution may not account for the GSL random number generator.

## Problem

The `PyPolyaGamma` instance is not pickle-able. This is problematic if one wants to pickle a model with an associated PPG instance or use multiprocessing, since each process needs its own copy of the code. Here is a minimal and complete example:

```python
# pickle_test.py

import pickle
from   pypolyagamma import PyPolyaGamma

class Model:
    def __init__(self):
        self.pg = PyPolyaGamma()

model = Model()
with open('test.pickle', 'wb+') as f:
    pickle.dump(model, f)
```

This will throw the following error:

```bash
Traceback (most recent call last):
  File "pickle_test.py", line 15, in <module>
    pickle.dump(model, f)
  File "stringsource", line 2, in pypolyagamma.pypolyagamma.PyPolyaGamma.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

I don't know enough Cython to fix this the correct way, but I'm happy to put together a PR if someone could provide direction.

## My solution

For anyone else who may have this issue, my workaround was to write a small wrapper:

```python
from pypolyagamma import PyPolyaGamma


class PyPolyaGammaWrapper:

    def __init__(self, seed=0, trunc=200):
        self.pg    = PyPolyaGamma(seed=seed, trunc=trunc)
        self.seed  = seed
        self.trunc = trunc

    def __reduce__(self):
        return self.__class__, (self.seed, self.trunc),

    def pgdraw(self, b, c):
        return self.pg.pgdraw(b, c)

    def pgdrawv(self, bs, cs, pgs):
        return self.pg.pgdrawv(bs, cs, pgs)
```

**Comment by macks22** [comment]
Another workaround I've found useful: if you have a model class storing `PyPolyaGamma` as an instance variable which is instantiated in the constructor, just switch to a `property` instead and store your random state in a `np.random.RandomState`. This ensure (1) the instance is never pickled, since properties are not pickled, and (2) pickling does not reset your random state back to what it was at construction. The latter guarantee is especially useful if you want to pass your model object around using pickle during inference, to avoid undue repetition of randomly generated numbers. For example:
```
import numpy as np
from pypolyagamma import PyPolyaGamma


class Model:
    def __init__(self, seed=42):
        self.rng = np.Random.RandomState(seed)

    @property
    def pg(self):
        seed = self.rng.randint(low=0, high=2 ** 32)
        return PyPolyaGamma(seed=seed)
```
This property can be used as a swap-in replacement for an instance attribute (i.e. it's accessible from `self` via `self.pg`), allowing you to easily modify existing code to make it pickleable.

**Comment by slinderman** [comment]
Thanks @macks22 and @gwgundersen.  I like @macks22's solution. The overhead in constructing the PyPolyaGamma object should be minimal compared to the cost of generating the samples, and all of the state of object should be encapsulated in the seed passed into the constructor.  

It would be a serious undertaking, but it would be nice, to eventually rewrite some of the underlying sampling code to follow the `numpy.random` design pattern.  I'm not sure how easy it is to extend that interface.
